server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://127.0.0.1:3306/hz-language?useUnicode=true&characterEncoding=utf-8

  jpa:
    database: mysql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hzxy.domain.pojo.entity


